# Generated by Django 2.1.7 on 2019-02-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinsurancecontract',
            name='cb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_cleaning.ClaimsBook'),
        ),
    ]
