# Generated by Django 2.1.7 on 2019-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0002_reinsurancecontract_cb'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='chrono',
            field=models.IntegerField(default=0),
        ),
    ]
