# Generated by Django 2.1.7 on 2019-03-08 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0004_auto_20190225_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyval',
            name='super_claims_book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ClaimsBook'),
        ),
    ]
