# Generated by Django 2.1.7 on 2019-03-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0005_keyval_super_claims_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='super_claims_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ClaimsBook'),
        ),
    ]
