# Generated by Django 2.1.7 on 2019-03-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0006_auto_20190308_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='value',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
