# Generated by Django 2.1.7 on 2019-03-18 07:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('table_cleaning', '0007_auto_20190308_1339'),
    ]

    operations = [
        migrations.RenameModel('KeyVal', 'KeyValEntry'),
        migrations.RenameModel('Claim', 'ClaimEntry')
    ]
