# Generated by Django 2.1.7 on 2019-03-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0008_auto_20190318_0848'),
    ]

    operations = [
        migrations.RenameModel('KeyValEntry', 'ClaimKeyVal'),
    ]
