# Generated by Django 2.1.7 on 2019-03-18 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0009_auto_20190318_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of insertion')),
                ('chrono', models.IntegerField(default=0)),
                ('claimsBook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ClaimsBook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(db_index=True, max_length=100)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ClaimEntry')),
                ('super_claims_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ClaimsBook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
