# Generated by Django 2.1.7 on 2019-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0010_registerentry_registerkeyval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerkeyval',
            name='claim',
        ),
        migrations.AddField(
            model_name='registerkeyval',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.RegisterEntry'),
            preserve_default=False,
        ),
    ]
