# Generated by Django 2.1.7 on 2019-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0011_auto_20190318_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimkeyval',
            name='value',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registerkeyval',
            name='value',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
