# Generated by Django 2.1.1 on 2019-04-17 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table_cleaning', '0012_auto_20190411_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of insertion')),
                ('is_aggregate', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of insertion')),
                ('chrono', models.IntegerField()),
                ('data_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.DataSheet')),
            ],
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('chrono', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.Entry')),
                ('super_data_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.DataSheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='claimentry',
            name='claimsBook',
        ),
        migrations.RemoveField(
            model_name='claimkeyval',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='claimkeyval',
            name='super_claims_book',
        ),
        migrations.RemoveField(
            model_name='claimsbook',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='registerentry',
            name='claimsBook',
        ),
        migrations.RemoveField(
            model_name='registerkeyval',
            name='register',
        ),
        migrations.RemoveField(
            model_name='registerkeyval',
            name='super_claims_book',
        ),
        migrations.AlterField(
            model_name='reinsurancecontract',
            name='cb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='table_cleaning.DataSheet'),
        ),
        migrations.DeleteModel(
            name='ClaimEntry',
        ),
        migrations.DeleteModel(
            name='ClaimKeyVal',
        ),
        migrations.DeleteModel(
            name='ClaimsBook',
        ),
        migrations.DeleteModel(
            name='RegisterEntry',
        ),
        migrations.DeleteModel(
            name='RegisterKeyVal',
        ),
    ]
