# Generated by Django 2.1.7 on 2019-04-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0013_auto_20190417_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyval',
            name='xls_type',
            field=models.IntegerField(default=1),
        ),
    ]
