# Generated by Django 2.1.7 on 2019-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0014_keyval_xls_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyval',
            name='tag',
            field=models.CharField(choices=[('UN', 'Undefined'), ('EML', 'EML'), ('ETB', 'EML/TSI band'), ('PR', 'Premium income'), ('YR', 'YEAR'), ('NR', '# of objects'), ('TSI', 'TSI'), ('LO', 'Loss'), ('ID', 'Id'), ('CA', 'Cause'), ('OC', 'Occupancy'), ('OT', 'Other')], db_index=True, default='UN', max_length=3),
        ),
    ]
