# Generated by Django 2.1.1 on 2019-04-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table_cleaning', '0016_auto_20190430_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinsurancePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XLLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb', models.FloatField()),
                ('ub', models.FloatField()),
                ('reinsurance_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ReinsurancePackage')),
            ],
        ),
        migrations.AddField(
            model_name='datasheet',
            name='reinsurance_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.ReinsurancePackage'),
        ),
    ]
