# Generated by Django 2.1.7 on 2019-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0017_auto_20190430_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='tag',
            field=models.CharField(choices=[('UN', 'Undefined'), ('EML', 'EML'), ('ETB', 'EML/TSI band'), ('PR', 'Premium income'), ('YR', 'YEAR'), ('NR', '# of objects'), ('TSI', 'TSI'), ('LO', 'Loss'), ('ID', 'Id'), ('CA', 'Cause'), ('OC', 'Occupancy'), ('SEG', 'Segment'), ('TAG', 'Tag'), ('OT', 'Other')], db_index=True, default='UN', max_length=3),
        ),
    ]
