# Generated by Django 2.1.1 on 2019-05-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0019_auto_20190502_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='xls_type',
            field=models.IntegerField(choices=[(0, 'Empty string'), (1, 'String'), (2, 'Float'), (3, 'Excel date'), (4, 'Boolean'), (5, 'Error'), (6, 'Zero float'), (7, 'String'), (8, 'Order')], default=1),
        ),
    ]
