# Generated by Django 2.1.1 on 2019-05-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0021_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document',
            field=models.FileField(upload_to='table_cleaning/resources/uploads'),
        ),
    ]
