# Generated by Django 2.1.1 on 2019-05-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0022_auto_20190516_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
