# Generated by Django 2.1.1 on 2019-05-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0023_uploadeddocument_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringKeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('tag', models.CharField(choices=[('UN', 'Undefined'), ('EML', 'EML'), ('ETB', 'EML/TSI band'), ('PR', 'Premium income'), ('YR', 'Year'), ('NR', '# of objects'), ('TSI', 'TSI'), ('LO', 'Loss'), ('ID', 'Id'), ('CA', 'Cause'), ('OC', 'Occupancy'), ('SEG', 'Segment'), ('TAG', 'Tag'), ('OT', 'Other')], db_index=True, default='UN', max_length=3)),
                ('value', models.CharField(db_index=True, max_length=100)),
                ('xls_type', models.IntegerField(choices=[(0, 'Empty string'), (1, 'String'), (2, 'Float'), (3, 'Excel date'), (4, 'Boolean'), (5, 'Error'), (6, 'Zero float'), (7, 'String'), (8, 'Order')], default=1)),
                ('chrono', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.Entry')),
                ('super_data_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.DataSheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='super_data_sheet',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
