# Generated by Django 2.1.1 on 2019-05-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0026_auto_20190523_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(db_index=True, max_length=500)),
                ('data_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.DataSheet')),
            ],
        ),
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stringkeyval',
            name='value',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
