# Generated by Django 2.1.1 on 2019-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0027_auto_20190528_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stringkeyval',
            name='value',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
