# Generated by Django 2.1.1 on 2019-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0028_auto_20190528_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='chrono',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='chrono',
            field=models.IntegerField(db_index=True),
        ),
    ]
