# Generated by Django 2.1.1 on 2019-07-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0029_auto_20190604_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InputTriangle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('triangle_name', models.CharField(max_length=200)),
                ('triangle_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=1000)),
                ('input_triangle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.InputTriangle')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='input_triangle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_cleaning.InputTriangle'),
        ),
    ]
