# Generated by Django 2.1.1 on 2019-08-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_cleaning', '0031_auto_20190704_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='xls_type',
            field=models.IntegerField(choices=[(0, 'Empty string'), (1, 'String'), (2, 'Float'), (3, 'Excel date'), (4, 'Boolean'), (5, 'Error'), (6, 'Zero float'), (7, 'String'), (8, 'Order'), (9, 'Triangle element')], default=1),
        ),
    ]
